'use client'

import { useEffect } from 'react'
import { MapContainer, Marker, Popup, Polyline, TileLayer, useMap } from 'react-leaflet'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'

type Appointment = { time: string; duration: number }
type Prospect = { name: string; street: string; housenumber?: string; postcode: string; city: string; lat: number; lng: number; distance?: number; website?: string; phone?: string; opening_hours?: string; source: 'lead' | 'crm'; category?: 'A' | 'B' | 'C'; appointment?: Appointment }
const colors = { A: '#ef4444', B: '#facc15', C: '#3b82f6', lead: '#b8f23f', crm: '#3b82f6' }
const key = (p: Prospect) => `${p.name}|${p.street}|${p.housenumber || ''}|${p.postcode}|${p.city}`
function icon(p: Prospect, visited: boolean, selected: boolean) { const color = p.source === 'crm' ? colors.crm : colors.lead; return L.divIcon({ className: '', html: `<span style="display:block;width:18px;height:18px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:${color};border:3px solid #17191b;opacity:${visited ? .4 : 1};filter:${visited ? 'grayscale(.8)' : 'none'};${selected ? 'box-shadow:0 0 0 4px rgba(23,25,27,.35);' : ''}"></span>`, iconSize: [22, 22], iconAnchor: [11, 22], popupAnchor: [0, -20] }) }
function Recenter({ center, selected }: { center: [number, number]; selected?: Prospect }) { const map = useMap(); useEffect(() => { map.setView(selected ? [selected.lat, selected.lng] : center, selected ? 15 : 12) }, [map, center, selected]); return null }
export function ProspectMap({ center, prospects, selected, onSelect, layers, setLayers, visited, visitKey, onToggleVisited, showVisited, setShowVisited, routeStops, onToggleRoute, onSchedule }: { center: [number, number]; prospects: Prospect[]; selected?: Prospect; onSelect: (p: Prospect) => void; layers: { lead: boolean; crm: boolean }; setLayers: React.Dispatch<React.SetStateAction<{ lead: boolean; crm: boolean }>>; visited: Record<string, boolean>; visitKey: (p: Prospect) => string; onToggleVisited: (p: Prospect) => void; showVisited: boolean; setShowVisited: (v: boolean) => void; routeStops: Prospect[]; onToggleRoute: (p: Prospect) => void; onSchedule: (p: Prospect, time: string) => void }) { const route = routeStops.map((p) => [p.lat, p.lng] as [number, number]); return <MapContainer center={center} zoom={12} scrollWheelZoom className="relative h-full w-full"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Recenter center={center} selected={selected} /><div className="leaflet-top leaflet-right z-[1000] m-3 rounded-xl border border-[#d4d8d2] bg-[#f8faf6]/95 p-3 text-xs shadow-lg"><p className="mb-2 font-semibold">Kartenfilter</p><label className="flex cursor-pointer items-center gap-2 py-1"><input type="checkbox" checked={layers.lead} onChange={(e) => setLayers((x) => ({ ...x, lead: e.target.checked }))} />Trüffel-Leads (OSM)</label><label className="flex cursor-pointer items-center gap-2 py-1"><input type="checkbox" checked={layers.crm} onChange={(e) => setLayers((x) => ({ ...x, crm: e.target.checked }))} />Bestandskunden (CRM)</label><label className="flex cursor-pointer items-center gap-2 py-1"><input type="checkbox" checked={showVisited} onChange={(e) => setShowVisited(e.target.checked)} />Besuchte Salons anzeigen</label></div>{route.length > 1 && <Polyline positions={route} pathOptions={{ color: '#b8f23f', weight: 4, dashArray: '8 8' }} />}{prospects.filter((p) => p.source === 'lead' ? layers.lead : layers.crm).map((p, i) => <Marker key={`${p.source}-${p.lat}-${p.lng}-${i}`} position={[p.lat, p.lng]} icon={icon(p, !!visited[visitKey(p)], routeStops.some((s) => key(s) === key(p)))} eventHandlers={{ click: () => onSelect(p) }}><Popup><strong>{p.name}</strong><br />{p.street} {p.housenumber}<br />{p.postcode} {p.city}<br />{p.source === 'lead' && <><label style={{display:'block',marginTop:6,fontSize:12}}>Termin <input type="time" defaultValue={p.appointment?.time || ''} onChange={(e) => e.target.value && onSchedule(p, e.target.value)} /></label><button type="button" onClick={() => onToggleRoute(p)} className="mt-2 rounded border px-2 py-1 text-xs">{routeStops.some((s) => key(s) === key(p)) ? '✓ In der Route' : '+ Route'}</button></>}<br /><button type="button" onClick={() => onToggleVisited(p)} className="mt-1 rounded border px-2 py-1 text-xs">{visited[visitKey(p)] ? '✓ Besucht' : '✓ Als besucht markieren'}</button></Popup></Marker>)}</MapContainer> }
export { key as prospectKey }
